### PR TITLE
Add option to match variants/alleles when annotating with VCF files. Thi...

### PR DESCRIPTION
**Pull request by jgoecks**
...s addresses issue #221.

### CODE REVIEW

**Comment by rronen** [comment]
+1!

**Comment by arq5x** [comment]
Thanks Jeremy!  Perhaps we should make matching by allele the default for VCF and have the user optionally decline to match by allele?  Also, since the GEMINI workflow now asks users to decompose and normalize the VCF, we should probably document that an annotation VCF should be transformed in kind.  Any thoughts? Cc @brentp?

**Comment by brentp** [comment]
Yes, this is a great idea and PR @jgoecks .
I think matching allele by default is a good idea.

Only possible nit is using `== True`. Can you change that to `is True` if it's needed or just replace `if boolean == True` with `if boolean`?

**Comment by jgoecks** [comment]
@brentp Fixed the boolean expression; my Python is rusty!

@arq5x @brentp I'm happy to make this option the default for VCFs. My thinking was to preserve the current behavior to avoid surprises for folks already using VCFs for annotations. However, if you two are OK with a change in default behavior, I can update this PR to make the default `true` with an option to disable it.

**Comment by brentp** [comment]
one other thought is that if one variant has REF=A, ALT=T and the other has REF=A, ALT=A,T, we'd either want those to match or give a warning about how we recommend splitting multiple alts. 
For this code, we could just support it in this case by checking for any intersection between the alts. Our aim has been to minimize false negatives, so I think that is reasonable.

Re defaulting this to true, I think that's also the best choice.

@arq5x ?

**Comment by arq5x** [comment]
In the case that the annotation VCF has multiple alts, I agree that we should try to match on the correct alternate allele, but we should also warn that decomposition, etc. is recommended.

**Comment by jgoecks** [comment]
Rebased and extended in #453

**Pull request closed without merging**
