### PR TITLE
use bcolz to save genotypes and run queries.

### PR DESCRIPTION
**Pull request by brentp**
cc @bw2 and @arq5x 

I have a quick prototype going. It currently works by running the sqlite query first and then using the variant_id to pull out the rows as needed from the genotype data stored in bcolz.

I'm still working on the useful part, which would be getting rows that meet the --gt-filter first using the bcolz.eval and teh numexpr machinery, but it already can calculate variant_id's that meet the --gt-filter . These will then be added to the query as  `"WHERE variant_id IN %s" % ",".join(ids)"`

If we allowed --gt-filters like: (gt_ref_depths[:, 0] >= 20) & (gt_ref_depths[:, 1] >= 22)
then this would work pretty much as-is--though `numexpr` doesn't allow indexing like that so we'd have to do:
```Python
gtr0 = gt_ref_depths[:, 0]
gtr1 = gt_ref_depths[:, 1]
bcolz.eval("(gtr0 >= 20) & (gtr1 >= 22)", user_dict=locals())
```
without that change, it has to use the numpy vm which won't be quite as fast.

Again, the current version works, it just doesn't do anything smart yet.
I haven't played with or developed  it enough to see a speed or disk use improvement, but I'm opening this for feedback.

### CODE REVIEW

**Comment by arq5x** [comment]
This looks really promising, Brent!  The only thing that worries me is the ``"WHERE variant_id IN %s" % ",".join(ids)"`` aspect, as that list of ids could be VERY large in the general (read whole genome, large cohort) case.  I worry that a) the query itself would exceed SQLite's query limit and that b) it might be slow.  When the v_id set is large, I think we would need to build an intermediate table of the variant_ids and then join to that.  Or maybe there is some other clever alternative? Or maybe I am worrying about nothing as usual.

**Comment by brentp** [comment]
So, this seems like a reasonable avenue. But I'm at the point where *MAJOR* changes to the code-base would be required to further pursue this. 
You're right that, eventually, we'd have to limit the number of ids in the `IN` clause, but I think that's doable. 

The latest commit allows identical queries to what are currently supported, e.g. : 
    --gt-filter "(gt_ref_depths.NA12889 >= 40 and gt_ref_depths.NA12877 >= 42)"
and it performs quite well--actually, it's pretty much instantaneous to run that query in bcolz to get the row_ids to send in the the `IN` sql query. What ruins the performance is pulling a single row at time from `bcolz`. We could pull X rows at a time, where X is the number of id's in the current `IN` chunk and this would greatly mitigate the problem.

I do see about 2 to 3X performance improvement, but I'm not sure if that is sufficient to continue. I think we'll face these same issues with GQT, in that we can do the genotype queries very quickly, but we still have to get back to the phenotype and annotation data in the database *AND* we have to keep the row-level genotype data available to be reported in the results.

This would be a good thing to think/chat about in detail--the advantage of this approach is that it starts to decouple the genotype info from the phenotype info which I think will ease future development.

**Comment by brentp** [comment]
I looked into this a bit more. The actually bcolz query to return a numpy array of the indexes (variant_id's) that pass a complex genotype filter is pretty much instant (0.02 seconds on a 100K db). However, pulling 40K records from the array (and even side-stepping some of the bcolz machinery which made it 2x as fast as the exposed method) takes 4 seconds. Once that is done, there is pretty much no overhead, because the eval()'s are all gone, but I think 1 second per 10K records is too slow. 

I still have one thing to try: http://bcolz.blosc.org/reference.html#whereblocks but I don't see an obvious route.

I think we will face the same issue with GQ--getting out the genotype data.

**Comment by bw2** [comment]
Just getting a chance to look through this code and I don't have much to add to your thorough analysis here. 
Regarding "it starts to decouple the genotype info from the phenotype info which I think will ease future development" - perhaps that's another good thing to discuss - and what the +/- are of storing genotypes together or separately from the variants and/or phenotypes.

**Comment by brentp** [comment]
closing this as it was the initial test-run of bcolz. superseded by current impl.

**Pull request closed without merging**
