### PR TITLE
Let the user know that temp files are being deleted.

### PR DESCRIPTION
**Pull request by brainstorm**
Hello Gemini,

After loading a beefy VCF file (~140MB) in a clean run, we discovered that `/tmp` ran out of space and the following files still were present after finishing "successfully?". GEMINI did not crash and the VCF seems properly loaded in the database:

```
[rvalls@fatnode01 tmp]$ ls -alh *
-rw-r--r-- 1 gcarrasco collab 190M Apr 21 14:21 final-merged.vcf.chunk0.db
-rw-r--r-- 1 gcarrasco collab 190M Apr 21 14:21 final-merged.vcf.chunk1.db
-rw-r--r-- 1 gcarrasco collab 174M Apr 21 14:19 final-merged.vcf.chunk2.db
-rw-r--r-- 1 gcarrasco collab 189M Apr 21 14:19 final-merged.vcf.chunk3.db
-rw-r--r-- 1 gcarrasco collab 189M Apr 21 14:21 final-merged.vcf.chunk4.db
-rw-r--r-- 1 gcarrasco collab 189M Apr 21 14:20 final-merged.vcf.chunk5.db
-rw-r--r-- 1 gcarrasco collab 187M Apr 21 14:19 final-merged.vcf.chunk6.db
-rw-r--r-- 1 gcarrasco collab 174M Apr 21 14:19 final-merged.vcf.chunk7.db
-rw-r--r-- 1 gcarrasco collab 190M Apr 21 14:21 final-merged.vcf.chunk8.db
-rw-r--r-- 1 gcarrasco collab 182M Apr 21 14:19 final-merged.vcf.chunk9.db
```

I'm adding a couple of print statements to at least inform the user. By the way, would you consider moving to `logging` instead of `print` statements?

@guillermo-carrasco

### CODE REVIEW

**Comment by brentp** [comment]
I'm fine with this change, but it doesn't address the problem you mention of stranded temp files.

we could probably do this reliably with https://docs.python.org/2/library/signal.html

**Comment by brainstorm** [comment]
That's totally right, should have checked `ENOSPC` or similar signals and do something about it... you want to do something clever like `lsof` the temp files, see which ones are *NOT* in use and delete them and notify the user or something else?

**Comment by brainstorm** [comment]
Btw, @guillermo-carrasco, are you sure you didn't get a `OSError` exception or similar when GEMINI finished importing that VCF? If not, it'll be tricky to catch this one... \<wildly_speculating\>unless there's a `sys.exit` somewhere that made GEMINI import exit prematurely making it seem like all was cleanly imported :-S\</wildly_speculating\>

**Comment by guillermo-carrasco** [comment]
@brainstorm nope, no errors at all :-/ But that was in the successful one. 

In the one that got out of space I did get errors, let me try to reproduce it and will paste the stacktrace here

**Comment by guillermo-carrasco** [comment]
This is it @brainstorm @brentp : 

```
pid 2809: 171219 variants processed.
pid 2803: 169999 variants processed.
sqlite3.OperationalError: database or disk is full
[E::bcf_hdr_read] invalid BCF2 magic string
/bin/sh: line 1:  2802 Done                    grabix grab final-merged.vcf.gz 856096 1027314
      2803 Segmentation fault      | gemini load_chunk -v - --skip-gerp-bp --skip-info-string --tempdir /var/tmp -o 856096 /var/tmp/final-merged.vcf.chunk5.db
pid 2800: 169999 variants processed.
sqlite3.OperationalError: database or disk is full
[E::bcf_hdr_read] invalid BCF2 magic string
/bin/sh: line 1:  2799 Done                    grabix grab final-merged.vcf.gz 684877 856095
      2800 Segmentation fault      | gemini load_chunk -v - --skip-gerp-bp --skip-info-string --tempdir /var/tmp -o 684877 /var/tmp/final-merged.vcf.chunk4.db
pid 2806: 169999 variants processed.
sqlite3.OperationalError: database or disk is full
[E::bcf_hdr_read] invalid BCF2 magic string
/bin/sh: line 1:  2805 Done                    grabix grab final-merged.vcf.gz 1027315 1198533
      2806 Segmentation fault      | gemini load_chunk -v - --skip-gerp-bp --skip-info-string --tempdir /var/tmp -o 1027315 /var/tmp/final-merged.vcf.chunk6.db
pid 2788: 169999 variants processed.
sqlite3.OperationalError: database or disk is full
[E::bcf_hdr_read] invalid BCF2 magic string
/bin/sh: line 1:  2787 Done                    grabix grab final-merged.vcf.gz 1 171219
      2788 Segmentation fault      | gemini load_chunk -v - --skip-gerp-bp --skip-info-string --tempdir /var/tmp -o 1 /var/tmp/final-merged.vcf.chunk0.db
Traceback (most recent call last):
  File "/cm/shared/apps/bcbio/20150720-devel/tools/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
    args.func(parser, args)
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
    gemini_load.load(parser, args)
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 49, in load
    load_multicore(args)
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 74, in load_multicore
    chunks = load_chunks_multicore(grabix_file, args)
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 252, in load_chunks_multicore
    wait_until_finished(procs)
  File "/cm/shared/apps/bcbio/20150720-devel/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 343, in wait_until_finished
    raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI chunk load
```

**Comment by guillermo-carrasco** [comment]
Sorry, forgot to mention: There are no residual files in `/tmp`. @brainstorm , maybe you looked at `tmp` _while_ the process was still running?

**Comment by brainstorm** [comment]
Oh, I see, we should catch the `sqlite3.OperationalError` then. Do we want to cleanup (`unlink`, `os.remove()`) given that error or just crash and leave files there for further debugging?

According to Linux's [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard), `/tmp` is destined to files that "`may be severely size restricted`". Therefore I would suggest using $PWD instead as a global default, at least it would not affect other programs or the OS/cluster node.

What do you think, @brentp?

**Comment by brentp** [comment]
users can change the tempdir with $TMPDIR or --tempdir so I don't want to hard-code that. Catching the sqlite error and then cleaning up seems reasonable.

**Comment by guillermo-carrasco** [comment]
yes, I actually solved this by using `--tempdir` and a bigger partition. In my opinion, its okay to remove the files after the error, which is what its done right now. Those are chunk files that cannot be reused other than to construct the final file, which will not be possible due to the lack of space. That's my understanding, could be wrong :-)

**Comment by brentp** [comment]
@guillermo-carrasco yes, I agree with that. I misread the thread.

**Comment by brainstorm** [comment]
@guillermo-carrasco, no, I had to `rm` the files manually myself after you finished the job since I'm root in that machine.

Alright, will catch the Exception and remove files then, thanks! ;)

**Comment by guillermo-carrasco** [comment]
hmm I'm not sure what happened there, there were no files after this one I posted :-/

**Comment by brainstorm** [comment]
Neither Guillermo nor me could reproduce this issue... bizarre, closing :/

**Comment by brentp** [comment]
weird things happen with NFS. this should alll be obviated once we have the new loader fully integrated anyway.

**Pull request closed without merging**
