### PR TITLE
WIP: Annotate With a VCF. Pulls from the INFO field

### PR DESCRIPTION
**Pull request by brentp**
this is in progress, but opened for discussion. Tests are pretty solid. I am working on docs. It allows a user to annotate with a vcf like:

     gemini annotate -f $VCF -t float -e BaseQRankSum -o mean $DB

where BaseQRankSum is pulled from the info field. Missing values (e.g. from a VCF record without that INFO field) are allowed.

### CODE REVIEW

**Comment by arq5x** [comment]
Looking good! Are multiple columns/INFO fields supported?  E.g., 

    gemini annotate -f $VCF -t float -e BaseQRankSum,AF -o mean,mean $DB

Also, I assume the user still has to also specify the column name with `-c`?

**Comment by brentp** [comment]
oh, right. I'll add tests for multiple columns.
the -c is optional and only if you want to override the name specified in -e

**Comment by rronen** [comment]
This would be an awesome(!) feature. I have been wishing for something like this for a while. 

On the same topic: even more awesome would be to make it possible to invoke this syntax as part of `load` (i.e., enabling pulling INFO fields into custom columns from the same VCF that's being loaded). As I understand it, this feature as-is would already make it possible with a second pass, but allowing to tack it onto the `load` would make it possible on a single pass (even better!).

Thanks for these awesome improvements (& supporting multiple ALTs).

**Comment by arq5x** [comment]
Roy,
Nice suggestion - in fact, @brentp and I were discussing the eventual support at load time earlier this week.  It is doable, but obviously requires a bit of clever engineering, since users will quickly want to load with >1 custom annotation file.  This could make the command line interface a bit of a mess, so we will have to think about how best to support this generally.  But rest assured it is on our minds.

**Comment by rronen** [comment]
Right, I agree that would definitely happen quickly. 

Although, I actually just had in mind the more limited subset of functionality where you only get to pull during `load` from the INFO of the same VCF you are loading (i.e., for columns/annotations from external VCF(s) you would still do it separately using `annotate`). This just saves you from reading the same VCF twice to load & annotate.

**Comment by arq5x** [comment]
Oh, I see.  Yeah, while the full INFO field is loaded to the DB, it would be nice to create fields on the fly. This is currently possible for custom VEP fields, so it could likely be easily made more general.

**Comment by brentp** [comment]
This has docs and is ready for review.

**Comment by rronen** [comment]
Yes, exactly! A general syntax for that would be awesome (with the many custom/special INFO fields out there in the wild ;).

**Comment by brentp** [comment]
@rronen could you open a new issue for that? 
This PR will provide a means for you to get that info (so to speak) but yes, we can support something on loading as well.

**Comment by arq5x** [comment]
This is ready to roll.  All in a day's work, eh @brentp ?

**Comment by rronen** [comment]
Thanks @brentp! Yes, just opened https://github.com/arq5x/gemini/issues/402.

**Comment by brentp** [comment]
@rronen , cheers. that seems do-able.

**Pull request merged**
