### PR TITLE
Use SIFT and Polyphen scores to select variant with the most severe i…

### PR DESCRIPTION
**Pull request by jgoecks**
…mpact. This fixes the bug that incorrectly sets sift and polyphen columns in the variants table. This bug occurred when two impacts had the same severity level but different sift/polyphen scores; when this happened, sift/polyphen information was taken from the first impact without regard to later sift/polyphen information.

### CODE REVIEW

**Comment by udp3f** [comment]
@jgoecks;
This should not have been the case. The logic here was, in case there is a tie i.e impacts with similar levels of severity, choice was made to pick the one that had a biotype of the kind 'protein-coding'  and all the other annotations for this particular transcript should have been represented i.e. polyphen etc.
Could you share the variant that was a problem in your case. I would like to look into it.
-Uma

**Comment by jgoecks** [comment]
The issue is that if the variant impacts multiple transcripts with 'protein coding' impact', then choosing the first one and using its SIFT and Polyphen—which is what is done without this patch—may not identify the most severe SIFT and Polyphen score. Here's an example variant that demonstrates this bug:

`chr2	29445247	.	C	T	.	.	AB=0.103448;AO=150;CIGAR=1X;DP=1450;RO=1300;TYPE=snp;HP=1;CSQ=missense_variant|Gac/Aac|D/N|ENSG00000171094|ALK|ENST00000453137|3/4|probably_damaging(0.924)|deleterious_low_confidence(0.01)|58/152|protein_coding,intron_variant|||ENSG00000171094|ALK|ENST00000431873||||-/450|protein_coding,missense_variant|Gac/Aac|D/N|ENSG00000171094|ALK|ENST00000389048|22/29|probably_damaging(0.972)|deleterious(0)|1160/1620|protein_coding	GT	0/1`

Both annotations are protein coding, but selecting the first one—as the code does without this patch—leads to setting the Polyphen impact as 'deleterious_low_confidence'. However, the second one shows that the most severe Polyphen impact is 'deleterious' and that is what should be set for this variant.

Hope I was clear, let me know if I can help in any other way.

**Comment by arq5x** [comment]
Thanks for the great example, @jgoecks !  Our plan is to completely refactor the VEP and snpeff logic in the release after next. I think your strategy is sound - however, I think we will hold off on merging in the code until after we refactor, so as to avoid duplicating effort. Does that sound reasonable to you? @brentp - any concerns?

**Comment by jgoecks** [comment]
@arq5x Sure, merge whenever it works best for you and the development team. I can use my fork in the meantime.

**Comment by brentp** [comment]
we do this as of the recent code change. All of the logic is handled in the geneimpacts module: https://github.com/brentp/geneimpacts/blob/078cf961fb13cc6d3bbef4957d39c93a53ffcfe3/geneimpacts/effect.py#L215

**Pull request closed without merging**
