### PR TITLE
fix loading of extra VEP annotations

### PR DESCRIPTION
**Pull request by jsh58**

### CODE REVIEW

**Comment by brentp** [comment]
@jsh58 I'll try this out. Were you having trouble with VEP annotations? Got a test-case I can add?

**Comment by jsh58** [comment]
Here is a one-variant VCF that fails to load.  This is because the "expected" VEP annotation fields aren't all listed first, which is implicitly assumed in line 76 in gemini_load_chunk.py.


Also, with that fixed, the "extra" fields fail to load at all because of the x.lower() bug (line 75).


________________________________

**Comment by brentp** [comment]
can you email it to bpederse@gmail.com ?

**Comment by brentp** [comment]
thanks for the test-case. I'm adding it to the repo along with additional changes related to this problem.

**Comment by brentp** [comment]
this has been incorporated into master

**Pull request closed without merging**
