### PR TITLE
genewise: only show variants that meet the require number of optional…

### PR DESCRIPTION
**Pull request by brentp**
… filters

reported by @jxchong

### CODE REVIEW

**Comment by jxchong** [comment]
Ah ok. Seems like this might have reverted the previous fix (that wouldn't output variants that didn't contribute to passing the gene level --min-filters).  I now get variants at 14365 and 14582 even though both are marked as only passing the required filters.

```
chrom	start	end	ref	alt	gene	impact	vep_feature_type	filter	gts	variant_filters	n_gene_variants	gene_filters
chrMT	14317	14318	T	C	MT-ND6	missense_variant	Transcript	None	T/T,T/T,T/C,./.,T/T,T/T,./.,./.,T/C,T/T,T/T	required[1],required[2],required[3],1	4	1,2
chrMT	14364	14365	C	T	MT-ND6	synonymous_variant	Transcript	None	C/C,C/C,C/C,C/C,C/C,C/C,C/C,T/T,C/C,C/C,C/C	required[1],required[2],required[3]	4	1,2
chrMT	14568	14569	G	A	MT-ND6	synonymous_variant	Transcript	SnpCluster	G/G,A/A,A/A,G/G,A/A,G/G,G/G,G/G,A/A,A/A,G/G	required[1],required[2],required[3],2	4	1,2
chrMT	14581	14582	A	G	MT-ND6	missense_variant	Transcript	SnpCluster	A/A,A/A,A/A,A/A,A/A,A/A,A/A,G/G,A/A,A/A,A/A	required[1],required[2],required[3]	4	1,2
```

**Comment by brentp** [comment]
hmm.  you sure you have the latest with that? can you show the query you were running?

**Comment by jxchong** [comment]
Yes I'm running commit 6fa548e

```
$ gemini gene_wise \
> --columns "chrom,start,end,ref,alt,gene,impact,vep_feature_type,filter,gts,gt_quals,gt_depths" \
> --where "chrom='chrMT'" \
> --gt-filter-required "(gt_depths).(phenotype==2).(>=6).(count >= 1) and (gt_quals).(phenotype==2).(>=20).(count >= 1)" \
> --gt-filter-required "(gt_quals).(=HET).(>=20).(any) or (gt_quals).(=HOM_ALT).(>=20).(any)" \
> --gt-filter-required "(gt_depths).(=HET).(>=6).(any) or (gt_quals).(=HOM_ALT).(>=6).(any)" \
> --gt-filter "gt_types.151854 == HET" \
> --gt-filter "gt_types.171139 == HOM_ALT" \
> --min-filters 2 \
> MT.VT.VEP.db
chrom	start	end	ref	alt	gene	impact	vep_feature_type	filter	gts	variant_filters	n_gene_variants	gene_filters
chrMT	14317	14318	T	C	MT-ND6	missense_variant	Transcript	None	T/T,T/T,T/C,./.,T/T,T/T,./.,./.,T/C,T/T,T/T	required[1],required[2],required[3],1	4	1,2
chrMT	14364	14365	C	T	MT-ND6	synonymous_variant	Transcript	None	C/C,C/C,C/C,C/C,C/C,C/C,C/C,T/T,C/C,C/C,C/C	required[1],required[2],required[3]	4	1,2
chrMT	14568	14569	G	A	MT-ND6	synonymous_variant	Transcript	SnpCluster	G/G,A/A,A/A,G/G,A/A,G/G,G/G,G/G,A/A,A/A,G/G	required[1],required[2],required[3],2	4	1,2
chrMT	14581	14582	A	G	MT-ND6	missense_variant	Transcript	SnpCluster	A/A,A/A,A/A,A/A,A/A,A/A,A/A,G/G,A/A,A/A,A/A	required[1],required[2],required[3]	4	1,2
```

**Comment by brentp** [comment]
can you share your db or vcf via email? the one you sent me only reports chrMT:14317 and chrMT:14568 for that query.

**Comment by jxchong** [comment]
Sent a dropbox invite.

**Comment by brentp** [comment]
thank you. can you check the latest commit? sorry for the repeated bugs. I think this time it's really resolved.

**Comment by jxchong** [comment]
Not quite right, I think. If I run --min-filters 1, then I get both variants I expect to get, but if I run --min-filters 2, I don't get any variants (but I should get both since each variant passes 1 filter, so that in total the gene MT-ND6 passes a minimum of 2 filters)


```
$ gemini gene_wise --columns "chrom,start,end,ref,alt,gene,impact,vep_feature_type,filter,gts,gt_quals,gt_depths" --where "chrom='chrMT'" --gt-filter-required "(gt_depths).(phenotype==2).(>=6).(count >= 1) and (gt_quals).(phenotype==2).(>=20).(count >= 1)" --gt-filter-required "(gt_quals).(=HET).(>=20).(any) or (gt_quals).(=HOM_ALT).(>=20).(any)" --gt-filter-required "(gt_depths).(=HET).(>=6).(any) or (gt_quals).(=HOM_ALT).(>=6).(any)" --gt-filter "gt_types.151854 == HET" --gt-filter "gt_types.171139 == HOM_ALT" --min-filters 1 MT.VT.VEP.db

chrom	start	end	ref	alt	gene	impact	vep_feature_type	filter	gts	variant_filters	n_gene_variants	gene_filters
chrMT	14317	14318	T	C	MT-ND6	missense_variant	Transcript	None	T/T,T/T,T/C,./.,T/T,T/T,./.,./.,T/C,T/T,T/T	required[1],required[2],required[3],1	2	1,2
chrMT	14568	14569	G	A	MT-ND6	synonymous_variant	Transcript	SnpCluster	G/G,A/A,A/A,G/G,A/A,G/G,G/G,G/G,A/A,A/A,G/G	required[1],required[2],required[3],2	2	1,2


$ gemini gene_wise --columns "chrom,start,end,ref,alt,gene,impact,vep_feature_type,filter,gts,gt_quals,gt_depths" --where "chrom='chrMT'" --gt-filter-required "(gt_depths).(phenotype==2).(>=6).(count >= 1) and (gt_quals).(phenotype==2).(>=20).(count >= 1)" --gt-filter-required "(gt_quals).(=HET).(>=20).(any) or (gt_quals).(=HOM_ALT).(>=20).(any)" --gt-filter-required "(gt_depths).(=HET).(>=6).(any) or (gt_quals).(=HOM_ALT).(>=6).(any)" --gt-filter "gt_types.151854 == HET" --gt-filter "gt_types.171139 == HOM_ALT" --min-filters 2 MT.VT.VEP.db
$ [no results]
```

**Comment by brentp** [comment]
could you have a look at the latest commit? If that doesn't fix it, then I'll have to look next week.

**Comment by jxchong** [comment]
Ok I think that did it!

I now get:

```
chrom	start	end	ref	alt	gene	impact	vep_feature_type	filter	gts	variant_filters	n_gene_variants	gene_filters
chrMT	14317	14318	T	C	MT-ND6	missense_variant	Transcript	None	T/T,T/T,T/C,./.,T/T,T/T,./.,./.,T/C,T/T,T/T	required[1],required[2],required[3],1	2	1,2
chrMT	14568	14569	G	A	MT-ND6	synonymous_variant	Transcript	SnpCluster	G/G,A/A,A/A,G/G,A/A,G/G,G/G,G/G,A/A,A/A,G/G	required[1],required[2],required[3],2	2	1,2
```

I'll try to do some more testing.

**Comment by jxchong** [comment]
So far so good.

**Comment by jxchong** [comment]
The one thing I'm noticing is that I cannot access per-sample gts, gt_depths, or gt_quals. I can print out all of the samples in the database if I use gts,gt_depths,gt_quals, but I cannot access gt_depths.sample12345 or gts.sample12345, etc. ```sqlalchemy.exc.NoSuchColumnError: "Could not locate column in row for column 'gts.151854'"```

I think this isn't a bug, just a potentially useful/missing feature.

**Comment by brentp** [comment]
added

**Pull request merged**
