### PR TITLE
Workaround for #427

### PR DESCRIPTION
**Pull request by bw2**
Workaround for errors during database loading that are caused by an incompatibility between SQLite file locking and some NFS filesystems. This adds a new --tempdir option that can be used to specify a non-NFS directory which can temporarily store the sqlite DBs while they're being populated. #427

### CODE REVIEW

**Comment by bw2** [comment]
For testing, I ran `gemini load --cores 128  --scheduler lsf`  on several vcfs. On one typical run, 18 of the 128 load_chunk jobs triggered the workaround code in `gemini_load_chunk.py` as a result of "database is locked" errors, and then 51 of the 127 merge jobs had "database is locked" or "disk I/O" errors triggering the workaround code in `gemini_merge_chunks.py`

**Comment by bw2** [comment]
The only things left unfinished AFAIK are the --tempdir help message, and possibly factoring out `os.path.join(args.tempdir, "%s.db" % uuid.uuid4())` into some global util function. 

Let me know what you think.

Thanks, 
-Ben

**Comment by bw2** [comment]
Did the testing before adding the --tempdir arg and didn't notice that it needed to be added to merge_chunks and load_chunk.

**Comment by bw2** [comment]
Just confirmed that the last 2 commits fixed the --tempdir arg by running with the --tempdir arg set to a directory on NFS, and getting the expected  `Exception: Attempted workaround for SQLite locking issue on NFS drives has failed. One possible reason is that the temp directory /path/to/dir is also on an NFS drive.`

**Comment by bw2** [comment]
Ok, confirmed that it creates a db successfully in lsf and multicore mode.
I think this PR is actually done now.

**Comment by brentp** [comment]
@bw2, this looks good. we are about to do a release. Once that is done, we'll update the dev branch and then, would you change this PR to be merged into dev? (I think you'll have to close this one and re-open into dev)

**Comment by bw2** [comment]
Sounds good. I will wait for the release. 
One other thing is, from what I can tell, `gemini_db.create_indices(..) ` is called in `[merge_chunks_multicore](https://github.com/arq5x/gemini/blob/master/gemini/gemini_load.py#L115)`, but not in `merge_chunks_ipython` , so the indices are never created. If you want I can add that into this PR.

**Comment by arq5x** [comment]
Very good catch - yeah, if you don't mind adding the index creation to the ipython function, that would be great, as it looks like ipython cluster DBs are not indexed at all. :(

**Comment by bw2** [comment]
I think this is done.. will resubmit it to the dev branch.

**Comment by brentp** [comment]
ok. at long last, I the latest rock/spec on luarocks is working.

**Comment by arq5x** [comment]
@brentp, not sure what you mean...

**Comment by brentp** [comment]
wrong issue.

**Comment by brentp** [comment]
@bw2, the dev branch is up-to-date now. Please re-open there.

**Pull request closed without merging**
