### PR TITLE
WIP: improve query performance

### PR DESCRIPTION
**Pull request by brentp**
Opening for feedback. **Mainly, what kinds of queries are people having performance problems with?**

improvement in this PR is from removing the use of eval. On a database with 450 samples, the worst-case scenario query of:

    gemini query -q "select chrom, start, (gts).(*) from variants" \
                            orig.db --gt-filter "(gt_depths).(*).(>=20).(all)

is **3 times faster**

A more likely query of:

    gemini query -q "select chrom, start, gts.89973, gts.89564, gts.89558, gts.89554, gts.89787 \
                      from variants" orig.db --gt-filter "(gt_depths).(*).(>=20).(all)" > /dev/null

is about **30% faster** (I have a low-hanging fruit to improve that).

So, if people can post examples or explanations of queries that are slow, I can optimize for those scenarios.

### CODE REVIEW

**Comment by arq5x** [comment]
Very cool!  We will have to give some thought to how to leverage this for the de_novo and auto_* tools, as they currenty build up eval masks based on sample relationships and expected genotypes.  E.g., de_novo:
https://github.com/arq5x/gemini/blob/master/gemini/gemini_subjects.py#L354-L434

**Comment by rronen** [comment]
Thanks for all this amazing work. It's great to see gemini moving so quickly!

Not sure this is different in any way from your example query above, but I often use `gt-filter` such as this when working with a tumor(s)/normal database:

```
"(gt_types).(phenotype==1).(==HOM_REF).(all) and\
 ((gt_types).(phenotype==2).(==HET).(any) or (gt_types).(phenotype==2).(==HOM_ALT).(any)) and\
 (gt_ref_depths).(phenotype==1).(>={min_nrm_ref}).(any) and\
 (gt_alt_depths).(phenotype==2).(>={min_tmr_alt}).(any) and\
 (gt_vafs).(phenotype==1).(<={max_nrm_vaf}).(all) and\
 (gt_vafs).(phenotype==2).(>={min_tmr_vaf}).(any)"
```

Which is not particularly performant, clearly :)

\*`gt_vafs` is an additional genotype/blob column I added that's useful with tumor samples, e.g. to query variants with sufficiently high VAF in tumor and sufficiently low in normal. It's computed on load as a simple function of the values in `gt_depths_ref` and `gt_depths_alt`.
\** In some ways, this query is an _on the fly_ version of the `set_somatic` tool.

**Comment by brentp** [comment]
With the current set of changes and this query:

    gemini query --header -q "select chrom, start, gts.89973, gts.89564, gts.89558, gts.89554, gts.89787\
             from variants" orig.db --gt-filter "((gt_depths).(*).(>=20).(all)) and (gt_types.89973 == HET)"

I get **1.937 secs** on this branch vs **4.589 secs** on master. I'm out of simple optimizations, but there are a few more things that can be done.

On this branch, I get:

```
 3015013 function calls (3012594 primitive calls) in 1.937 seconds

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     4988    0.665    0.000    0.774    0.000 GeminiQuery.py:751(_group_samples_by_genotype)
     4989    0.261    0.000    3.065    0.001 {eval}
      303    0.130    0.000    4.425    0.015 GeminiQuery.py:617(next)
    14964    0.130    0.000    0.130    0.000 {cPickle.loads}
    14964    0.116    0.000    0.116    0.000 {zlib.decompress}
  2301190    0.110    0.000    0.110    0.000 {method 'append' of 'list' objects}
     5379    0.109    0.000    2.782    0.001 {all}
     4989    0.053    0.000    0.131    0.000 GeminiQuery.py:1184(_tokenize_query)
   179585    0.041    0.000    0.066    0.000 GeminiQuery.py:1185(<genexpr>)
   183151    0.038    0.000    0.038    0.000 {method 'split' of 'str' objects}
     4988    0.021    0.000    0.021    0.000 {locals}
    14964    0.014    0.000    0.260    0.000 compression.py:15(unpack_genotype_blob)
     4989    0.013    0.000    0.161    0.000 GeminiQuery.py:1187(_query_needs_genotype_info)
```


compared to master:
```
        10272878 function calls (9876368 primitive calls) in 4.589 seconds

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     4988    1.320    0.000    2.071    0.000 gemini_utils.py:421(partition_by_fn)
  2284504    0.391    0.000    0.391    0.000 GeminiQuery.py:762(<lambda>)
618573/224483    0.287    0.000    0.858    0.000 GeminiQuery.py:1222(flatten)
     6499    0.287    0.000    2.915    0.000 {eval}
    39904    0.278    0.000    0.278    0.000 {zlib.decompress}
    39904    0.267    0.000    0.267    0.000 {cPickle.loads}
  2284504    0.242    0.000    0.242    0.000 GeminiQuery.py:761(<lambda>)
   394094    0.216    0.000    0.369    0.000 abc.py:128(__instancecheck__)
793336/793335    0.203    0.000    0.572    0.000 {isinstance}
      303    0.194    0.001    6.907    0.023 GeminiQuery.py:616(next)
  2301190    0.120    0.000    0.120    0.000 {method 'append' of 'list' objects}
   394114    0.106    0.000    0.106    0.000 _weakrefset.py:70(__contains__)
     5379    0.099    0.000    2.608    0.000 {all}
     4989    0.081    0.000    0.981    0.000 GeminiQuery.py:1192(_tokenize_query)
```

**Comment by brentp** [comment]
@rronen thanks for the example. any chance you could share your database?

**Comment by rronen** [comment]
The data I've been loading lately is under some restrictions, sorry I can't be more helpful on this.

**Comment by brentp** [comment]
yeah, I realized that was probably the case after posting. We'll get something with a pedigree file internally and I'll use your query as a test-case.

**Comment by arq5x** [comment]
Awesome work brent.  say hi to T and Noor and have a great weekend.

**Comment by brentp** [comment]
the latest changes get the query above down to 1.53 seconds (from 4.56 originally).

these optimizations should apply to most queries so I think 2X should be common and likely much faster for others. I have yet to look at the pedigree stuff. 

```
 2546591 function calls (2544172 primitive calls) in 1.532 seconds

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     4988    0.550    0.000    0.655    0.000 GeminiQuery.py:748(_group_samples_by_genotype)
     4989    0.240    0.000    2.918    0.001 {eval}
      303    0.123    0.000    3.906    0.013 GeminiQuery.py:617(next)
  2301190    0.106    0.000    0.106    0.000 {method 'append' of 'list' objects}
     5379    0.101    0.000    2.659    0.000 {all}
    10278    0.094    0.000    0.094    0.000 {cPickle.loads}
    10278    0.094    0.000    0.094    0.000 {zlib.decompress}
    10278    0.010    0.000    0.198    0.000 compression.py:15(unpack_genotype_blob)
     3206    0.010    0.000    0.017    0.000 gemini_subjects.py:30(_set_fields_from_row)
       13    0.008    0.001    0.014    0.001 zipfile.py:803(_RealGetContents)
   346/81    0.006    0.000    0.017    0.000 sre_parse.py:388(_parse)
        4    0.005    0.001    0.015    0.004 gemini_utils.py:26(<dictcomp>)
```

**Comment by brentp** [comment]
@rronen 
you could run: python -m cProfile -s tottime /full/path/to/gemini .... args ...
with your query and paste the first 30 lines of profiling output.

**Comment by rronen** [comment]
Hi @brentp,

Sorry this took so long, I was a little swamped with other things. The output below is from running the profiler for a python program that calls `GeminiQuery` via the python api with a query like the one I mentioned above. It's a very tough query (worst case in many ways) as it's genotype fields only and thus no use of any index. 

Here are the first 30 lines (database used here has ~75k entries from two tumor exomes and a matched normal exome).

```
28492267 function calls (24946142 primitive calls) in 79.641 seconds

Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
5600111/2056073   15.641    0.000   44.846    0.000 GeminiQuery.py:1115(flatten)
    27063   13.867    0.001   16.477    0.001 {eval}
7101815/7101814   10.898    0.000   29.221    0.000 {isinstance}
  3544039   10.819    0.000   18.323    0.000 abc.py:128(__instancecheck__)
      835    4.595    0.006   80.856    0.097 GeminiQuery.py:515(next)
  3544067    4.492    0.000    4.492    0.000 _weakrefset.py:70(__contains__)
    27053    3.571    0.000   50.047    0.002 GeminiQuery.py:1085(_tokenize_query)
  3548074    3.016    0.000    3.016    0.000 {getattr}
   243468    2.725    0.000    2.725    0.000 {cPickle.loads}
    27053    2.092    0.000   53.970    0.002 GeminiQuery.py:1089(_query_needs_genotype_info)
  2059182    1.830    0.000    1.830    0.000 {method 'startswith' of 'str' objects}
  1542628    1.630    0.000    1.630    0.000 {method 'split' of 'str' objects}
   243468    1.138    0.000    5.365    0.000 compression.py:16(unpack_genotype_blob)
   243468    0.934    0.000    0.934    0.000 {zlib.decompress}
   245600    0.572    0.000    0.572    0.000 {numpy.core.multiarray.array}
    81563    0.277    0.000    1.212    0.000 {all}
    77166    0.227    0.000    0.845    0.000 {any}
    27056    0.178    0.000    0.178    0.000 {locals}
      205    0.087    0.000    0.254    0.001 doccer.py:12(docformat)
    27079    0.078    0.000    0.115    0.000 {map}
    70067    0.056    0.000    0.056    0.000 {method 'append' of 'list' objects}
        1    0.055    0.055    0.075    0.075 qt4_compat.py:2(<module>)
```

Let me know if you need anything else!

**Comment by brentp** [comment]
thanks @rronen . 
I've optimized a lot of those slow points at the top of your list. I just tried a similar query 

```
(gt_types).(phenotype == 1).(==HOM_REF).(all) and \
   ((gt_types).(phenotype==2).(==HET).(any) \
     or (gt_types).(phenotype==2).(==HOM_ALT).(any)) and \
  (gt_ref_depths).(phenotype==1).(>=20).(any) and \
  (gt_alt_depths).(phenotype==2).(>=20).(any)
```

and get **74 seconds on master** vs. **13.8 seconds** with identical md5sums on the output, so I think you'll have at least 3X improvement. 

For that query, I don't see much room left for improvement without splitting the eval:

```
         666181 function calls (664016 primitive calls) in 13.810 seconds

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    29866    7.837    0.000   10.101    0.000 {eval}
    89935    1.739    0.000    1.739    0.000 {cPickle.loads}
      341    1.641    0.005   15.003    0.044 GeminiQuery.py:613(next)
    89935    0.522    0.000    0.522    0.000 {zlib.decompress}
    89935    0.441    0.000    2.701    0.000 compression.py:15(unpack_genotype_blob)
    29865    0.378    0.000    0.462    0.000 GeminiQuery.py:745(_group_samples_by_genotype)
    77782    0.297    0.000    0.982    0.000 {any}
    30284    0.159    0.000    0.606    0.000 {all}
    71762    0.097    0.000    0.097    0.000 {method 'append' of 'list' objects}
```

so I'm going to add tests so this will be ready to merge.

**Comment by rronen** [comment]
Thanks @brentp!! Looking forward to trying the new version!

**Comment by arq5x** [comment]
Very excited about this PR.

**Pull request merged**
