### PR TITLE
Problem with ClinVar causal alt allele handling

### PR DESCRIPTION
**Pull request by nuada**
Hi,

When loading VCF into GEMINI 0.12.1 I got this error:
```
Traceback (most recent call last):
  File "/usr/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/usr/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/usr/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/usr/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/usr/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 117, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/usr/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 305, in _prepare_variation
    clinvar_info = annotations.get_clinvar_info(var)
  File "/usr/share/gemini/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 541, in get_clinvar_info
    clinvar_causal_allele += hit.alt.split(',')[causal_allele_number - 1]
IndexError: list index out of range
```
Most recent release of ClinVar for GEMINI contains only decomposed alternative alleles but value of `causal_allele_number` is loaded from CLNALLE info field.

Comment in [annotations.py:528](https://github.com/nuada/gemini/blob/master/gemini/annotations.py#L528) is invalid because:
```
zcat clinvar_20150305.tidy.vcf.gz | grep -Eo 'CLNALLE=.' | sort | uniq -c 
    227 CLNALLE=-
   3468 CLNALLE=.
    160 CLNALLE=0
 108825 CLNALLE=1
   4244 CLNALLE=2
    373 CLNALLE=3
      2 CLNALLE=4
```

So instead of:
```
clinvar_causal_allele = hit.alt.split(',')[causal_allele_number - 1]
```
should be:
```
clinvar_causal_allele = hit.alt
```

Does it make sense or I'm missing something?

### CODE REVIEW

**Comment by brentp** [comment]
Hi @nuada , thanks for reporting. This fix looks reasonable, but can you send me the genomic position CHR, POS of a variant that results in this error? I'd like to make sure I understand what is going on since the clinvar preprocessing is fairly complex.

**Comment by brentp** [comment]
So, when I run that, I get:
```
$ zcat clinvar_20150305.tidy.vcf.gz | grep -Eo 'CLNALLE=.' | sort | uniq -c
227 CLNALLE=-
3468 CLNALLE=.
160 CLNALLE=0
113444 CLNALLE=1
```
I'm checking further.

**Comment by brentp** [comment]
I had an older version of the clinvar up on AWS. I have uploaded a new one.  You can run:

    rm clinvar_*.tidy.*
    wget https://s3.amazonaws.com/gemini-annotations/clinvar_20150305.tidy.vcf.gz
    wgethttps://s3.amazonaws.com/gemini-annotations/clinvar_20150305.tidy.vcf.gz.tbi

from your data directory.

**Comment by nuada** [comment]
ClinVar update fixed this problem, 

Thank you @brentp

**Comment by brentp** [comment]
thanks for reporting!

**Pull request closed without merging**
